name: Publish Python Package ğŸš€

on:
  push:
    branches:
      - main

jobs:
  package:
    name: Publish Python Package ğŸš€
    runs-on: ubuntu-latest

    steps:
    - name: Checkout ğŸ›ï¸
      uses: actions/checkout@v4

    - name: Set up Python ğŸ”§
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install build dependencies ğŸ“¦
      run: pip install setuptools wheel twine

    - name: Build package ğŸ—ï¸
      run: python setup.py sdist bdist_wheel

    - name: Publish Python Package ğŸš€
      env:
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      run: python -m twine upload dist/*
